### ISSUE TITLE
License

### ISSUE THREAD

**Issue by john-wigg** [jknipper/mcp4728_program_address#1]
I would like to bundle a slightly modified version of this code with a project I'm working on to make setting up the DACs easier. However, since there is no license attached to this repository, I'm a bit hesitant to do so.

It would greatly clear things up for me if you added a license. Thank you!

**Comment by jknipper** [comment]
Hi John, just use it, I don't care what you do with it. If you release it at open-source later on even better. Cheers!

**Comment by john-wigg** [comment]
Thanks a lot for the quick answer! (And thanks for the great sketch as well :P)
